### ISSUE TITLE
Incorrect purchase at time

### ISSUE THREAD

**Issue by antonym8** [antonym8/Grouppal-Franchise#7]
Franchise purchase at time is incorrect in franchise transaction details page and in pdf

![Screenshot_20240125_132330](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/3c42f2a1-daf2-4fb4-9c6e-c74335e1dd28)
![Screenshot_20240125_132408](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/2d983bbc-1740-49df-a522-51d6ac0818ea)
![Screenshot_20240125_132424](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/4ec31c65-d155-4ba0-86b9-ad7de521a2d4)

**Comment by m8dharma** [comment]
Fixed

**Comment by antonym8** [comment]
Not fixed. Purchase time is 6.09 PM, but in details page time showing as 5.35PM

![Screenshot_20240125_180948](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/ff486f0a-0412-4a22-a0c8-612c3c2e171c)
![Screenshot_20240125_181008](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/9f71fc1d-8040-4b13-a22f-a449d3ee0c09)
