### ISSUE TITLE
Revenue history

### ISSUE THREAD

**Issue by antonym8** [antonym8/Grouppal-Franchise#8]
Franchise dashboard page showing other pincode's revenue history

![Screenshot_20240125_132535](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/aff59aac-bb25-46ae-8a95-9fd7a15a7358)

**Comment by m8dharma** [comment]
fixed

**Comment by antonym8** [comment]
Not fixed. Earning showing as 0, but revenue history showing some other revenues. It's looks confusing

![Screenshot_20240125_181200](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/17865cd0-7e11-49c3-923b-02761bd427e4)
